"""empty message

Revision ID: 009ada47b250
Revises: 4c645c8c51ac
Create Date: 2022-06-02 04:44:18.996427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009ada47b250'
down_revision = '4c645c8c51ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('first_name', sa.String(length=150), nullable=True))
    op.add_column('car', sa.Column('last_name', sa.String(length=150), nullable=True))
    op.add_column('car', sa.Column('address', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'address')
    op.drop_column('car', 'last_name')
    op.drop_column('car', 'first_name')
    # ### end Alembic commands ###
