"""empty message

Revision ID: 4c645c8c51ac
Revises: 8ced71ae79e8
Create Date: 2022-06-02 04:36:31.334901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c645c8c51ac'
down_revision = '8ced71ae79e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
